# Generated by Django 4.1.2 on 2022-10-27 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myTasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='idNummer',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
